//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_media_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant_tbl
    {
        public int Id { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_name { get; set; }
        public string a_address { get; set; }
        public string a_contact_num { get; set; }
        public string a_email_add { get; set; }
        public string a_user { get; set; }
        public string a_pass { get; set; }
    }
}
