//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_media_Guide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class job_interviewEntities : DbContext
    {
        public job_interviewEntities()
            : base("name=job_interviewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_tbl> admin_tbl { get; set; }
        public virtual DbSet<applicant_tbl> applicant_tbl { get; set; }
        public virtual DbSet<video_tbl> video_tbl { get; set; }
        public virtual DbSet<tbl_message> tbl_message { get; set; }
    }
}
