//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_media_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public int Id { get; set; }
        public string tbl_name { get; set; }
        public string tbl_email { get; set; }
        public string tbl_msg { get; set; }
    }
}
