//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multi_media_Guide.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class video_tbl
    {
        public int Id { get; set; }
        public string v_title { get; set; }
        public string v_description { get; set; }
        public string v_category { get; set; }
        public string v_video_link { get; set; }
        public string image_path { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
